import matplotlib.pyplot as plt
import pandas as pd

df = pd.read_csv('C:\\Users\\Димон\\PycharmProjects\\МатПлотЛиб\\company_sales_data.csv')
month_list = df['month_number'].tolist()
total_profit = df['total_profit'].tolist()
plt.plot(month_list, total_profit, c='green', ls='-.', lw=2.5, marker='o', markersize=10, markerfacecolor='white')
plt.xticks(month_list)
plt.xlabel('Month number', fontsize=15)
plt.ylabel('Total Profit', fontsize=15)
plt.title('2020 total profit data', fontweight='bold', fontsize=20)
plt.show()

monthlist = df['month_number'].tolist()
facecreamsales = df['facecream'].tolist()
facewashsales = df['facewash'].tolist()
toothpastesales = df['toothpaste'].tolist()
bathingsoapsales = df['bathingsoap'].tolist()
shampoosales = df['shampoo'].tolist()
moisturizersales = df['moisturizer'].tolist()
plt.plot(monthlist, facecreamsales, label='face cream sales', lw=2, marker='o')
plt.plot(monthlist, facewashsales, label='face wash sales', lw=2, marker='o')
plt.plot(monthlist, toothpastesales, label='tooth paste sales', lw=2, marker='o')
plt.plot(monthlist, bathingsoapsales, label='bathing soap sales', lw=2, marker='o')
plt.plot(monthlist, shampoosales, label='shampoo sales', lw=2, marker='o')
plt.plot(monthlist, moisturizersales, label='moisturizer sales', lw=2, marker='o')
plt.xticks(monthlist)
plt.xlabel('Month number', fontsize=15)
plt.ylabel('Units sold', fontsize=15)
plt.title('Sales data', fontweight='bold', fontsize=20)
plt.legend(loc='best')
plt.grid(c='blue', lw=0.2)
plt.show()

monthlist = df['month_number'].tolist()
toothpasteSales = df['toothpaste'].tolist()
plt.scatter(monthlist, toothpasteSales, color='black')
plt.xlabel('Month number', fontsize=15)
plt.ylabel('Toothpaste Sales', fontsize=15)
plt.xticks(monthlist)
plt.grid(color='blue', ls='--', lw=0.2)
plt.title('Toothpaste sales', fontsize=20, fontweight='bold')
plt.show()

monthlist = df['month_number'].tolist()
facecreamsales = df['facecream'].tolist()
facewashsales = df['facewash'].tolist()
plt.bar([a - 0.25 for a in monthlist], facecreamsales, width=0.25, label='Face cream Sales', align='edge', color='pink')
plt.bar([a + 0.25 for a in monthlist], facewashsales, width=-0.25, label='Face wash Sales', align='edge',
        color='skyblue')
plt.xlabel('Month number', fontsize=13)
plt.ylabel('Sales', fontsize=13)
plt.title('Face care products sales', fontsize=15, fontweight='bold')
plt.xticks(monthlist)
plt.grid(c='black', lw=0.20, alpha=0.5)
plt.legend(loc='best')
plt.show()

total_profit = df['total_profit'].tolist()
labels = ['low', 'average', 'Good', 'Best']
profit_range = [150000, 175000, 200000, 225000, 250000, 300000, 350000]
plt.hist(total_profit, profit_range, lw=0.2)
plt.xlabel('Profit range', fontsize=15)
plt.ylabel('Actual profits', fontsize=15)
plt.title('2020 total profit range data', fontweight='bold', fontsize=20)
plt.show()

labels = ['FaceCream', 'FaseWash', 'ToothPaste', 'Bathing soap', 'Shampoo', 'Moisturizer']
salesData = [df['facecream'].sum(), df['facewash'].sum(), df['toothpaste'].sum(),
             df['bathingsoap'].sum(), df['shampoo'].sum(), df['moisturizer'].sum()]
plt.axis("equal")
plt.pie(salesData, labels=labels, autopct='%1.1f%%')
plt.legend(loc='best')
plt.show()

monthlist = df['month_number'].tolist()
bathingsoapsales = df['bathingsoap'].tolist()
facewashsales = df['facewash'].tolist()
f, (ax1, ax2) = plt.subplots(2, 1, sharex=True)
ax1.plot(monthlist, bathingsoapsales, label='Bathing soap sales', lw=1.5, c='red', marker='o')
ax2.plot(monthlist, facewashsales, label='Face wash sales', lw=1.5, c='skyblue', marker='o')
plt.xlabel('Month number', fontsize=15)
plt.ylabel('Units sold', fontsize=15)
plt.xticks(monthlist)
plt.suptitle('Bathing soap and face wash sales comparison', fontsize=15, fontweight='bold')
ax1.legend(loc='best')
ax2.legend(loc='best')
plt.show()

monthlist = df['month_number'].tolist()
facecreamsales = df['facecream'].tolist()
facewashsales = df['facewash'].tolist()
toothpastesales = df['toothpaste'].tolist()
bathingsoapsales = df['bathingsoap'].tolist()
shampoosales = df['shampoo'].tolist()
moisturizersales = df['moisturizer'].tolist()
plt.plot([], [], c='blue', label='face cream sales')
plt.plot([], [], c='black', label='face wash sales')
plt.plot([], [], c='skyblue', label='tooth paste sales')
plt.plot([], [], c='red', label='bathing soap sales')
plt.plot([], [], c='pink', label='shampoo sales')
plt.plot([], [], c='purple', label='moisturizer sales')
plt.stackplot(monthlist, facecreamsales, facewashsales, toothpastesales, bathingsoapsales, shampoosales,
              moisturizersales, colors=['b', 'black', 'skyblue', 'r', 'pink', 'purple'])
plt.xticks(monthlist)
plt.xlabel('Month number', fontsize=15)
plt.ylabel('Units sold', fontsize=15)
plt.title('Sales data', fontweight='bold', fontsize=20)
plt.legend(loc='upper left')
plt.show()
